server:
  port: 9091
spring:
  application:
    name: CALCULATION-SERVICE
winnerService:
  url: http://WINNER-SERVICE/winner/
lotery:
  filepath: C:\Users\sales\Documents\projects\LOTTERY-SYSTEM\CALCULATION-SERVICE\lotery.json
