server:
  port: 9091
spring:
  application:
    name: CALCULATION-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
winnerService:
  url: http://WINNER-SERVICE/winner/
lotery:
  filepath: C:\Users\sales\Documents\projects\LOTTERY-SYSTEM\CALCULATION-SERVICE\lotery.json
